CREATE TABLE DEPARTMENTS ( 
	DEPT_NO VARCHAR(30) PRIMARY KEY,
	DEPT_NAME VARCHAR(30)
);

CREATE TABLE TITLES (
	TITLE_ID VARCHAR(30) PRIMARY KEY,
	TITLE VARCHAR(225)
);

CREATE TABLE EMPLOYEES (
	EMP_NO INT PRIMARY KEY,
	EMP_TITLE_ID VARCHAR(30),
	BIRTH_DATE VARCHAR(10), --MM/DD/YYYY << 10 CHAR
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	SEX VARCHAR(1),
	HIRE_DATE VARCHAR(10),
	FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES (TITLE_ID)
);

CREATE TABLE DEPT_EMP (
	EMP_NO INT,
	DEPT_NO VARCHAR(30),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO)
);

CREATE TABLE DEPT_MANAGER (
	DEPT_NO VARCHAR(30),
	EMP_NO INT,
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO)
);

CREATE TABLE SALARIES (
	EMP_NO INT,
	SALARY INT,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO)
);